# Generated by Django 5.0.1 on 2026-03-16 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('customers', '0001_initial'),
        ('inventory', '0003_producto_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('año', models.SmallIntegerField(verbose_name='Año')),
                ('placa', models.CharField(blank=True, default='', max_length=20, verbose_name='Placa')),
                ('color', models.CharField(blank=True, default='', max_length=50, verbose_name='Color')),
                ('notas', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motos', to='customers.clienteprofile', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Moto del cliente',
                'verbose_name_plural': 'Motos de clientes',
                'db_table': 'taller_motos_cliente',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServicioMoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=25, unique=True, verbose_name='Folio')),
                ('descripcion', models.TextField(verbose_name='Descripción del servicio')),
                ('status', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_PROCESO', 'En proceso'), ('COTIZACION_EXTRA', 'Cotización extra pendiente'), ('LISTO', 'Listo para entrega'), ('ENTREGADO', 'Entregado')], default='RECIBIDO', max_length=20, verbose_name='Estado')),
                ('pago_status', models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de pago'), ('PAGADO', 'Pagado')], default='PENDIENTE_PAGO', max_length=20, verbose_name='Estado de pago')),
                ('mano_de_obra', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Mano de obra')),
                ('total_refacciones', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total refacciones')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('metodo_pago', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia')], max_length=15, null=True, verbose_name='Método de pago')),
                ('monto_pagado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto pagado')),
                ('cambio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cambio')),
                ('cliente_notificado', models.BooleanField(default=False, verbose_name='Cliente notificado')),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de recepción')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Inicio de trabajo')),
                ('fecha_listo', models.DateTimeField(blank=True, null=True, verbose_name='Trabajo terminado')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_asignados_por', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_recibidos', to=settings.AUTH_USER_MODEL, verbose_name='Cajero / Recepcionista')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='customers.clienteprofile', verbose_name='Cliente')),
                ('mecanico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Mecánico')),
                ('moto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='taller.motocliente', verbose_name='Moto')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='branches.sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'taller_servicios',
                'ordering': ['-fecha_recepcion'],
            },
        ),
        migrations.CreateModel(
            name='ServicioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('REFACCION', 'Refacción cotizada'), ('MANO_OBRA', 'Mano de obra'), ('EXTRA', 'Refacción extra')], max_length=15, verbose_name='Tipo')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('aprobado', models.BooleanField(default=True, help_text='False para ítems EXTRA hasta que el cliente los autorice', verbose_name='Aprobado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicio_items_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicio_items', to='inventory.producto', verbose_name='Producto')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='taller.serviciomoto', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Ítem de servicio',
                'verbose_name_plural': 'Ítems de servicio',
                'db_table': 'taller_servicio_items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudRefaccionExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('motivo', models.TextField(verbose_name='Motivo / Justificación')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente de autorización'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('respondido_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta')),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_extra_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Mecánico')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_extra', to='inventory.producto', verbose_name='Producto')),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_extra_respondidas', to=settings.AUTH_USER_MODEL, verbose_name='Respondido por')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_extra', to='taller.serviciomoto', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Solicitud de refacción extra',
                'verbose_name_plural': 'Solicitudes de refacción extra',
                'db_table': 'taller_solicitudes_extra',
                'ordering': ['-created_at'],
            },
        ),
    ]
