# Generated by Django 5.0.1 on 2026-03-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motocliente',
            name='numero_serie',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Número de serie'),
        ),
    ]
