# Generated by Django 5.0.1 on 2026-03-21 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0002_add_numero_serie_to_motocliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciomoto',
            name='checklist_recepcion',
            field=models.JSONField(blank=True, default=list, verbose_name='Checklist de recepción'),
        ),
        migrations.CreateModel(
            name='ServicioImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='taller/imagenes/%Y/%m/', verbose_name='Imagen')),
                ('descripcion', models.CharField(blank=True, default='', max_length=200, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='taller.serviciomoto', verbose_name='Servicio')),
                ('subida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagenes_taller', to=settings.AUTH_USER_MODEL, verbose_name='Subida por')),
            ],
            options={
                'verbose_name': 'Imagen de servicio',
                'verbose_name_plural': 'Imágenes de servicio',
                'db_table': 'taller_servicio_imagenes',
                'ordering': ['created_at'],
            },
        ),
    ]
