# Generated by Django 5.0.1 on 2026-03-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0003_add_checklist_and_imagenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciomoto',
            name='fecha_entrega_estimada',
            field=models.DateField(blank=True, null=True, verbose_name='Entrega estimada'),
        ),
        migrations.AddField(
            model_name='serviciomoto',
            name='notas_internas',
            field=models.TextField(blank=True, default='', verbose_name='Notas internas'),
        ),
    ]
