# Generated by Django 5.0.1 on 2026-03-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0004_add_notas_fecha_estimada'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciomoto',
            name='es_reparacion',
            field=models.BooleanField(default=False, verbose_name='Es reparación'),
        ),
        migrations.AlterField(
            model_name='serviciomoto',
            name='status',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_DIAGNOSTICO', 'En diagnóstico'), ('EN_PROCESO', 'En proceso'), ('COTIZACION_EXTRA', 'Cotización extra pendiente'), ('LISTA_PARA_ENTREGAR', 'Lista para entregar'), ('LISTO', 'Entregada'), ('ENTREGADO', 'Entregado')], default='RECIBIDO', max_length=20, verbose_name='Estado'),
        ),
    ]
