# Generated by Django 5.0.1 on 2026-03-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0005_add_es_reparacion_and_new_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciomoto',
            name='status',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_DIAGNOSTICO', 'En diagnóstico'), ('EN_PROCESO', 'En proceso'), ('COTIZACION_EXTRA', 'Cotización extra pendiente'), ('LISTA_PARA_ENTREGAR', 'Lista para entregar'), ('CANCELADO', 'Cancelada'), ('LISTO', 'Entregada'), ('ENTREGADO', 'Entregado')], default='RECIBIDO', max_length=20, verbose_name='Estado'),
        ),
    ]
