# Generated by Django 5.0.1 on 2026-03-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0006_add_cancelado_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciomoto',
            name='diagnostico_mecanico',
            field=models.TextField(blank=True, default='', verbose_name='Diagnóstico del mecánico'),
        ),
        migrations.AddField(
            model_name='serviciomoto',
            name='refacciones_requeridas',
            field=models.TextField(blank=True, default='', verbose_name='Refacciones requeridas'),
        ),
    ]
