# Generated by Django 5.0.1 on 2026-03-26 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0007_add_diagnostico_cancelado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciomoto',
            name='archivado',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Archivado en historial'),
        ),
        migrations.AddField(
            model_name='serviciomoto',
            name='archivado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_archivadas', to=settings.AUTH_USER_MODEL, verbose_name='Archivado por'),
        ),
        migrations.AddField(
            model_name='serviciomoto',
            name='fecha_archivado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de archivado'),
        ),
        migrations.AlterField(
            model_name='serviciomoto',
            name='status',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_DIAGNOSTICO', 'En diagnóstico'), ('EN_PROCESO', 'En proceso'), ('COTIZACION_EXTRA', 'Cotización extra pendiente'), ('LISTA_PARA_ENTREGAR', 'Lista para entregar'), ('CANCELADO', 'Cancelada'), ('LISTO', 'Lista para entregar'), ('ENTREGADO', 'Entregado')], default='RECIBIDO', max_length=20, verbose_name='Estado'),
        ),
    ]
