# Generated by Django 5.0.1 on 2026-03-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0009_serviciomoto_tracking_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciomoto',
            name='diagnostico_listo',
            field=models.BooleanField(default=False, help_text='El mecánico marcó el diagnóstico como completo y listo para autorizar', verbose_name='Diagnóstico enviado a recepción'),
        ),
    ]
