# Generated by Django 5.0.1 on 2026-03-26 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_add_servicio_to_ventaitem'),
        ('taller', '0010_serviciomoto_diagnostico_listo'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciomoto',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_taller', to='sales.venta', verbose_name='Venta registrada'),
        ),
    ]
