# Generated by Django 5.0.1 on 2026-03-28 22:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionfiscalsede',
            name='iva_tasa',
            field=models.DecimalField(decimal_places=2, default=Decimal('16.00'), help_text='Porcentaje de IVA aplicado en los tickets (ej. 16.00 para 16%)', max_digits=5, verbose_name='Tasa de IVA (%)'),
        ),
    ]
