# Generated by Django 5.0.1 on 2026-03-20 19:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('inventory', '0004_stock_stock_sede_qty_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚüÜñÑ\\s\\-]+$')], verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Categoría de Servicio',
                'verbose_name_plural': 'Categorías de Servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CatalogoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚüÜñÑ\\s\\-]+$')], verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('precio_base', models.DecimalField(decimal_places=2, help_text='Precio base del servicio en MXN', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio base')),
                ('duracion_estimada_minutos', models.PositiveIntegerField(default=30, help_text='Duración estimada en minutos', verbose_name='Duración estimada (min)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_catalogo_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='catalogo_servicios.categoriaservicio', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Servicio del Catálogo',
                'verbose_name_plural': 'Catálogo de Servicios',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CatalogoServicioRefaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('es_opcional', models.BooleanField(default=False, help_text='Si es True, la refacción es opcional y no bloquea la disponibilidad del servicio', verbose_name='Es opcional')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='en_servicios', to='inventory.producto', verbose_name='Producto')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refacciones', to='catalogo_servicios.catalogoservicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Refacción del Servicio',
                'verbose_name_plural': 'Refacciones del Servicio',
                'ordering': ['es_opcional', 'producto__name'],
                'unique_together': {('servicio', 'producto')},
            },
        ),
        migrations.CreateModel(
            name='PrecioServicioSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_override', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio override')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_servicio', to='branches.sede', verbose_name='Sede')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_sede', to='catalogo_servicios.catalogoservicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Precio de Servicio por Sede',
                'verbose_name_plural': 'Precios de Servicios por Sede',
                'unique_together': {('servicio', 'sede')},
            },
        ),
    ]
