# Generated by Django 5.0.1 on 2026-03-21 04:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogoservicio',
            name='duracion_estimada_minutos',
            field=models.PositiveIntegerField(blank=True, help_text='Duración estimada en minutos (opcional)', null=True, verbose_name='Duración estimada (min)'),
        ),
        migrations.AlterField(
            model_name='catalogoservicio',
            name='precio_base',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio base del servicio en MXN (opcional)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio base'),
        ),
    ]
