# Generated by Django 5.0.1 on 2026-05-22 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.EmailField(max_length=254, verbose_name='Destinatario (real)')),
                ('asunto', models.CharField(max_length=300, verbose_name='Asunto')),
                ('tipo', models.CharField(choices=[('TICKET_VENTA', 'Ticket de venta'), ('TICKET_SERVICIO', 'Ticket de servicio'), ('ESTATUS', 'Aviso de estatus'), ('RECEPCION', 'Recepción / seguimiento'), ('LISTO', 'Moto lista'), ('CREDENCIALES', 'Credenciales'), ('RESET', 'Restablecer contraseña'), ('OTRO', 'Otro')], default='OTRO', max_length=20, verbose_name='Tipo')),
                ('enviado', models.BooleanField(default=False, verbose_name='Enviado')),
                ('error', models.CharField(blank=True, default='', max_length=1000, verbose_name='Error')),
                ('html', models.TextField(blank=True, default='', verbose_name='Cuerpo HTML')),
                ('texto', models.TextField(blank=True, default='', verbose_name='Cuerpo texto')),
                ('contexto', models.JSONField(blank=True, default=dict, verbose_name='Contexto (para reenviar)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correos', to='customers.clienteprofile', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Registro de correo',
                'verbose_name_plural': 'Registro de correos',
                'db_table': 'customers_email_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['destinatario', 'created_at'], name='emaillog_dest_fecha_idx'), models.Index(fields=['cliente', 'created_at'], name='emaillog_cli_fecha_idx')],
            },
        ),
    ]
