# Generated by Django 5.0.1 on 2026-03-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('inventory', '0003_producto_imagen'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['sede', 'quantity'], name='stock_sede_qty_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['producto', 'sede'], name='stock_producto_sede_idx'),
        ),
    ]
