# Generated by Django 5.0.1 on 2026-03-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auditoríainventario_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriainventario',
            name='fecha',
            field=models.DateField(verbose_name='Fecha de visita'),
        ),
    ]
