# Generated by Django 5.0.1 on 2026-03-17 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('customers', '0001_initial'),
        ('sales', '0004_reportecaja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aperturacaja',
            index=models.Index(fields=['cajero', 'status'], name='apertura_cajero_status_idx'),
        ),
        migrations.AddIndex(
            model_name='aperturacaja',
            index=models.Index(fields=['sede', 'status'], name='apertura_sede_status_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['sede', 'status'], name='venta_sede_status_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['sede', 'created_at'], name='venta_sede_created_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['cajero', 'status'], name='venta_cajero_status_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['created_at', 'status'], name='venta_created_status_idx'),
        ),
    ]
