# Generated by Django 5.0.1 on 2026-03-20 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_servicios', '0001_initial'),
        ('inventory', '0004_stock_stock_sede_qty_idx_and_more'),
        ('sales', '0005_aperturacaja_apertura_cajero_status_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaitem',
            name='catalogo_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_items', to='catalogo_servicios.catalogoservicio', verbose_name='Servicio del catálogo'),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='tipo',
            field=models.CharField(choices=[('PRODUCTO', 'Producto'), ('SERVICIO', 'Servicio de catálogo')], default='PRODUCTO', max_length=10, verbose_name='Tipo de ítem'),
        ),
        migrations.AlterField(
            model_name='ventaitem',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='venta_items', to='inventory.producto', verbose_name='Producto'),
        ),
    ]
