# Generated by Django 5.0.1 on 2026-05-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_add_servicio_to_ventaitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturacaja',
            name='monto_inicial',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Efectivo con el que se abrió la caja (copiado del código).', max_digits=12, verbose_name='Fondo inicial'),
        ),
        migrations.AddField(
            model_name='codigoapertura',
            name='monto_inicial',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Efectivo con el que se abre la caja para dar cambio.', max_digits=12, verbose_name='Fondo inicial'),
        ),
        migrations.AddField(
            model_name='reportecaja',
            name='diferencia',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Contado − esperado. Negativo = faltante, positivo = sobrante.', max_digits=12, verbose_name='Diferencia'),
        ),
        migrations.AddField(
            model_name='reportecaja',
            name='efectivo_contado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Efectivo físico contado al cerrar (lo captura el cajero).', max_digits=12, null=True, verbose_name='Efectivo contado'),
        ),
        migrations.AddField(
            model_name='reportecaja',
            name='efectivo_esperado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fondo inicial + ventas en efectivo.', max_digits=12, verbose_name='Efectivo esperado en caja'),
        ),
        migrations.AddField(
            model_name='reportecaja',
            name='monto_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Fondo inicial'),
        ),
    ]
