"""
Sales Models — MotoQFox POS
============================
Venta          — sale header (sede, cajero, totals, payment)
VentaItem      — sale line items (producto, quantity, unit_price)
CodigoApertura — temporary 6-digit code generated by encargado to allow cashier to open register
AperturaCaja   — active cash register session for a cashier
"""
from django.db import models
from django.db.models import Q


class Venta(models.Model):

    class MetodoPago(models.TextChoices):
        EFECTIVO      = 'EFECTIVO',      'Efectivo'
        TARJETA       = 'TARJETA',       'Tarjeta'
        TRANSFERENCIA = 'TRANSFERENCIA', 'Transferencia'

    class Status(models.TextChoices):
        COMPLETADA = 'COMPLETADA', 'Completada'
        CANCELADA  = 'CANCELADA',  'Cancelada'

    sede         = models.ForeignKey(
        'branches.Sede', on_delete=models.PROTECT,
        related_name='ventas', verbose_name='Sede'
    )
    cajero       = models.ForeignKey(
        'users.CustomUser', on_delete=models.PROTECT,
        related_name='ventas', verbose_name='Cajero'
    )
    subtotal     = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Subtotal')
    descuento    = models.DecimalField(max_digits=10, decimal_places=2, default=0, verbose_name='Descuento')
    total        = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Total')
    metodo_pago  = models.CharField(
        max_length=20, choices=MetodoPago.choices,
        default=MetodoPago.EFECTIVO, verbose_name='Método de pago'
    )
    monto_pagado = models.DecimalField(
        max_digits=10, decimal_places=2, default=0,
        verbose_name='Monto pagado'
    )
    cambio       = models.DecimalField(
        max_digits=10, decimal_places=2, default=0,
        verbose_name='Cambio'
    )
    status       = models.CharField(
        max_length=20, choices=Status.choices,
        default=Status.COMPLETADA, verbose_name='Estado'
    )
    cliente      = models.ForeignKey(
        'customers.ClienteProfile', on_delete=models.SET_NULL,
        null=True, blank=True, related_name='ventas', verbose_name='Cliente'
    )
    puntos_ganados = models.PositiveIntegerField(default=0, verbose_name='Puntos ganados')
    notas        = models.TextField(blank=True, default='', verbose_name='Notas')
    created_at   = models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')

    class Meta:
        db_table = 'sales_ventas'
        ordering = ['-created_at']
        verbose_name = 'Venta'
        verbose_name_plural = 'Ventas'
        indexes = [
            models.Index(fields=['sede', 'status'],     name='venta_sede_status_idx'),
            models.Index(fields=['sede', 'created_at'], name='venta_sede_created_idx'),
            models.Index(fields=['cajero', 'status'],   name='venta_cajero_status_idx'),
            models.Index(fields=['created_at', 'status'], name='venta_created_status_idx'),
        ]

    def __str__(self):
        return f'Venta #{self.id} — {self.sede.name} — ${self.total}'


class VentaItem(models.Model):
    """One line of a sale: producto × quantity at a fixed unit_price."""
    venta      = models.ForeignKey(
        Venta, on_delete=models.CASCADE,
        related_name='items', verbose_name='Venta'
    )
    producto   = models.ForeignKey(
        'inventory.Producto', on_delete=models.PROTECT,
        related_name='venta_items', verbose_name='Producto'
    )
    quantity   = models.PositiveIntegerField(verbose_name='Cantidad')
    unit_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Precio unitario')
    subtotal   = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Subtotal')

    class Meta:
        db_table = 'sales_venta_items'
        verbose_name = 'Ítem de Venta'
        verbose_name_plural = 'Ítems de Venta'

    def __str__(self):
        return f'[Venta #{self.venta_id}] {self.producto.sku} ×{self.quantity}'


# ─── Apertura de Caja ─────────────────────────────────────────────────────────

class CodigoApertura(models.Model):
    """
    Temporary 6-digit code generated by encargado.
    Valid for 30 minutes; any cashier of the same sede can use it.
    """
    sede         = models.ForeignKey(
        'branches.Sede', on_delete=models.PROTECT,
        related_name='codigos_apertura', verbose_name='Sede'
    )
    generado_por = models.ForeignKey(
        'users.CustomUser', on_delete=models.PROTECT,
        related_name='codigos_generados', verbose_name='Generado por'
    )
    codigo       = models.CharField(max_length=6, verbose_name='Código')
    expires_at   = models.DateTimeField(verbose_name='Expira el')
    created_at   = models.DateTimeField(auto_now_add=True, verbose_name='Generado el')

    class Meta:
        db_table = 'sales_codigos_apertura'
        ordering = ['-created_at']
        verbose_name = 'Código de apertura'
        verbose_name_plural = 'Códigos de apertura'

    def __str__(self):
        return f'Código {self.codigo} — {self.sede.name}'


class AperturaCaja(models.Model):
    """Active cash register session. One open session per cashier at a time."""

    class Status(models.TextChoices):
        ABIERTA = 'ABIERTA', 'Abierta'
        CERRADA = 'CERRADA', 'Cerrada'

    sede           = models.ForeignKey(
        'branches.Sede', on_delete=models.PROTECT,
        related_name='aperturas_caja', verbose_name='Sede'
    )
    cajero         = models.ForeignKey(
        'users.CustomUser', on_delete=models.PROTECT,
        related_name='aperturas_caja', verbose_name='Cajero'
    )
    autorizado_por = models.ForeignKey(
        'users.CustomUser', on_delete=models.PROTECT,
        related_name='cajas_autorizadas', verbose_name='Autorizado por'
    )
    codigo         = models.ForeignKey(
        CodigoApertura, on_delete=models.PROTECT,
        verbose_name='Código usado'
    )
    fecha_apertura = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de apertura')
    fecha_cierre   = models.DateTimeField(null=True, blank=True, verbose_name='Fecha de cierre')
    status         = models.CharField(
        max_length=10, choices=Status.choices,
        default=Status.ABIERTA, verbose_name='Estado'
    )

    class Meta:
        db_table = 'sales_aperturas_caja'
        ordering = ['-fecha_apertura']
        verbose_name = 'Apertura de caja'
        verbose_name_plural = 'Aperturas de caja'
        indexes = [
            models.Index(fields=['cajero', 'status'], name='apertura_cajero_status_idx'),
            models.Index(fields=['sede',   'status'], name='apertura_sede_status_idx'),
        ]
        constraints = [
            models.UniqueConstraint(
                fields=['cajero'],
                condition=Q(status='ABIERTA'),
                name='unique_cajero_caja_abierta'
            )
        ]

    def __str__(self):
        return f'Caja {self.cajero.get_full_name()} — {self.sede.name} [{self.status}]'


# ─── Reporte de Cierre de Caja ────────────────────────────────────────────────

class ReporteCaja(models.Model):
    """
    PDF report generated automatically when a cashier closes their register.
    Accessible by the cashier, the sede's encargado, and the administrator.
    """
    apertura        = models.OneToOneField(
        AperturaCaja, on_delete=models.PROTECT,
        related_name='reporte', verbose_name='Apertura de caja'
    )
    archivo         = models.FileField(
        upload_to='reportes_caja/%Y/%m/', verbose_name='Archivo PDF'
    )
    total_ventas        = models.PositiveIntegerField(default=0)
    total_canceladas    = models.PositiveIntegerField(default=0)
    monto_total         = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    monto_efectivo      = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    monto_tarjeta       = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    monto_transferencia = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    total_descuentos    = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    created_at          = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'sales_reportes_caja'
        ordering = ['-created_at']
        verbose_name = 'Reporte de caja'
        verbose_name_plural = 'Reportes de caja'

    def __str__(self):
        return f'Reporte #{self.id} — {self.apertura.cajero.get_full_name()} — {self.apertura.sede.name}'
