# Generated by Django 5.0.1 on 2026-03-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_loginauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMINISTRATOR', 'Administrador'), ('ENCARGADO', 'Encargado de Sede'), ('JEFE_MECANICO', 'Jefe de Mecánicos'), ('MECANICO', 'Mecánico'), ('WORKER', 'Trabajador'), ('CASHIER', 'Cajero'), ('CUSTOMER', 'Cliente')], default='CUSTOMER', max_length=20, verbose_name='Rol'),
        ),
        migrations.AddIndex(
            model_name='loginauditlog',
            index=models.Index(fields=['email', 'timestamp'], name='audit_email_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='loginauditlog',
            index=models.Index(fields=['event_type', 'timestamp'], name='audit_event_ts_idx'),
        ),
    ]
